- name: ibm/granite-3-8b-instruct
  context_length: 131072
  max_output_tokens: 8192
  input_cost: 0.2
  output_cost: 0.2

- name: ibm/granite-3-2-8b-instruct
  context_length: 131072
  max_output_tokens: 16384
  input_cost: 0.2
  output_cost: 0.2

- name: ibm/granite-3-3-8b-instruct
  context_length: 131072
  max_output_tokens: 16384
  input_cost: 0.2
  output_cost: 0.2

- name: ibm/granite-4-h-small
  context_length: 131072
  max_output_tokens: 8192
  input_cost: 0.06
  output_cost: 0.25

- name: meta-llama/llama-3-2-11b-vision-instruct
  context_length: 131072
  max_output_tokens: 8192
  input_cost: 0.35
  output_cost: 0.35

- name: meta-llama/llama-3-405b-instruct
  context_length: 131072
  max_output_tokens: 4096
  input_cost: 5.0
  output_cost: 16.0

- name: meta-llama/llama-3-2-90b-vision-instruct
  context_length: 131072
  max_output_tokens: 8192
  input_cost: 2.0
  output_cost: 2.0

- name: meta-llama/llama-3-3-70b-instruct
  context_length: 131072
  max_output_tokens: 8192
  input_cost: 0.71
  output_cost: 0.71

- name: mistralai/mistral-medium-2505
  context_length: 131072
  max_output_tokens: 16384
  input_cost: 3.0
  output_cost: 10.0

- name: mistralai/mistral-small-3-1-24b-instruct-2503
  context_length: 128000
  max_output_tokens: 16384
  input_cost: 0.1
  output_cost: 0.3

- name: ibm/granite-guardian-3-8b
  context_length: 8192
  max_output_tokens: 8192
  input_cost: 0.2
  output_cost: 0.2

